app.controller("EmployeeController",function($scope){
$scope.employees=[
{"name":"ramesh","empid":"101","dept":"UI","sal":"1000","address":"JUBLIEE"},
{"name":"Chaith","empid":"102","dept":"JAVA","sal":"2000","address":"AMPT"},
{"name":"SURESH","empid":"103","dept":"DOTNET","sal":"1500","address":"MADHAPUR"},
{"name":"saranya","empid":"104","dept":"DATABASE","sal":"3000","address":"MEHDP"},
{"name":"Ramya","empid":"105","dept":"PHP","sal":"2000","address":"SEC"}
]
});